version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: coffee_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: coffee_db
      MYSQL_USER: coffee_user
      MYSQL_PASSWORD: coffee_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  nodeapp:
    build: .
    container_name: coffee_api
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: coffee_db
      DB_USER: coffee_user
      DB_PASSWORD: coffee_pass
      PORT: 3000
    depends_on:
      - mysql
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  mysql_data:
